name: pipeline
on: [push]
jobs:
  test:
    runs-on: ['self-hosted']
    steps:
      - id: test
        run: echo "Test!!!"
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
